name = "transferpathway"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "transferpath-database"
database_id = "f74d009b-772f-49f3-a29e-977981335762"
migrations_dir = "drizzle"


[assets]
directory = ".open-next/assets"
binding = "ASSETS"

